#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Filter bash histfile."""

from argparse import ArgumentParser, Namespace
from io import TextIOWrapper
from os import environ
from os.path import expanduser, expandvars, isfile, realpath
from sys import exit as Exit
from sys import stderr as STDERR
from sys import stdout as STDOUT
from typing import Any, Dict, List, Tuple

import argcomplete as acp

MAXSIZE = int(environ.get("HISTFILESIZE", "32500"))
VERBOSE = False


def error(*msg, **kwargs) -> None:
    """Print msg to STDERR."""
    if not msg:
        return

    end: str = kwargs.get("end", "\n")
    sep: str = kwargs.get("sep", " ")
    flush: bool = kwargs.get("flush", False)

    print(*msg, end=end, sep=sep, flush=flush, file=STDERR)


def die(code: int = 0, *msg, **kwargs) -> None:
    """Kill the program with a given code, and print a message if given."""
    try:
        code = int(code)
    except Exception:
        code = 1

    if msg:
        end: str = kwargs.get("end", "\n")
        sep: str = kwargs.get("sep", " ")
        flush: bool = kwargs.get("flush", False)

        if code != 0:
            error(*msg, end=end, sep=sep, flush=flush)
        else:
            print(*msg, end=end, sep=sep, flush=flush)

    Exit(code)


def verb_print(verbose: bool, *data: object, **kwargs) -> None:
    """Print if verbose is turned on"""
    if not (verbose and data):
        return

    end: str = kwargs.get("end", "\n")
    sep: str = kwargs.get("sep", " ")
    flush: bool = kwargs.get("flush", False)
    file = kwargs.get("file", STDOUT)

    print(*data, end=end, sep=sep, file=file, flush=flush)


def get_histfile_path(p: str = "") -> str:
    """Retrieve histfile path.

    Parameters
    ----------
    p : str, default=""
        Path to histfile

    Returns
    -------
    str
    """
    p = p.strip(" ").strip("\n") if p is str else ""

    if p != "":
        p = realpath(expanduser(p) if (p[0] == "~" or "$" in p) else p)
    elif "HISTFILE" in environ.keys():
        p = realpath(environ["HISTFILE"])
    else:
        p = realpath(expandvars("$HOME") + "/.bash_history")

    if isfile(p):
        return p

    raise FileNotFoundError


def line_strip(data: str) -> str:
    """Strip data string"""
    if data is not str:
        try:
            data = str(data)
        except Exception:
            raise TypeError("(filter_histfile - line_strip): data unavailable!")

    return data.rstrip("\n").strip(" ").rstrip("/")


def filter(verbose: bool, f: TextIOWrapper) -> str:
    """Filter histfile"""
    if not f.readable():
        raise ValueError("(filter_histfile - filter): file not readable!")

    buffer = list()
    data = line_strip(f.readline())
    while data != "":
        buffer.append(data)
        data = line_strip(f.readline())

    buffer.reverse()
    new_buffer = list()

    # Remove duplicates
    for v in buffer:
        if v not in new_buffer:
            new_buffer.append(v)

    del buffer

    new_buffer.reverse()
    for i, v in enumerate(new_buffer):
        if v in ("\n", "") or len(v) <= 1:
            new_buffer.pop(i)
        elif v[-1] != "\n":
            new_buffer[i] += "\n"

    # Keep lines up to a certain max
    if len(new_buffer) > MAXSIZE:
        new_buffer = new_buffer.copy()[-MAXSIZE:]

    res = "".join(new_buffer)

    if res[-1] != "\n":
        res += "\n"

    verb_print(verbose, res)
    return res


def gen_args(
        args: List[List[str]],
        opts: List[Tuple[Dict[str, Any], acp.completers.FilesCompleter | None]]
) -> Namespace:
    """Generate argparse arguments from special dict."""
    if not (args and opts):
        raise AssertionError("(filter_histfile - gen_args): Bad arguments!")

    parser = ArgumentParser(
        prog="filter_histfile",
        description="Filter histfile and get rid of duplicates"
    )
    completer = False
    for arg, dest in zip(args, opts):
        d = dest[0]
        c = dest[1]
        if not c or c is None:
            parser.add_argument(*arg, **d)
        else:
            completer = True
            parser.add_argument(*arg, **d).completer = c

    if completer:
        acp.autocomplete(parser)

    return parser.parse_args()


def main() -> int:
    """Execute main workflow"""
    code = 0
    dests: List[List[str]] = [
        ["-v", "--verbose"],
        ["-f", "--file"],
    ]
    kwargs: List[Tuple[Dict[str, Any], acp.completers.FilesCompleter | None]] = [
        (
            {
                "action": "store_true",
                "help": "Verbose mode",
                "dest": "verbose",
                "required": False,
            },
            None,
        ),
        (

            {
                "help": "Absolute path to histfile",
                "dest": "fpath",
                "default": "",
                "nargs": 1,
            },
            acp.completers.FilesCompleter(),
        )
    ]

    args = gen_args(dests, kwargs)
    fpath: str = str(args.fpath) if args.fpath is not str else args.fpath
    verbose: bool = args.verbose

    try:
        histfile = open(get_histfile_path(fpath), "r")
        verb_print(verbose, f"Opened histfile `{fpath}`")
        new_data = filter(verbose, histfile)
        histfile.close()

        if new_data != "":
            histfile = open(get_histfile_path(fpath), "w")
            histfile.write(new_data)
            histfile.close()

    except ValueError:
        code = 4
    except FileNotFoundError:
        code = 127
    except KeyboardInterrupt:
        code = 2
    except Exception:
        code = 1

    return code


if __name__ == "__main__":
    Exit(main())
