#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Filter bash histfile."""
import sys
from argparse import ArgumentParser, Namespace
from io import TextIOWrapper
from os import environ
from os.path import expanduser, expandvars, isfile, realpath
from sys import stderr, stdout
from typing import Any, Dict, List, TextIO, Tuple

import argcomplete as ac

MAXSIZE: int = int(environ.get("HISTFILESIZE", "32500"))
VERBOSE: bool = False


class ArgData:
    """
    Data to be passed to the argument parser.

    Parameters
    ----------
    args : List[str]
        List of options related to this argument (e.g. ``-v``).
    kwargs : Dict[str, Any]
        Dictionary of arguments passed to an argument parser option.
    completer : argcomplete.FilesCompleter, optional, default=None
        Optional completer.

    Attributes
    ----------
    args : List[str]
        List of options related to this argument (e.g. ``-v``).
    kwargs : Dict[str, Any]
        Dictionary of arguments passed to an argument parser option.
    completer : argcomplete.FilesCompleter, optional, default=None
        Optional completer.
    """

    args: List[str]
    kwargs: Dict[str, Any]
    completer: ac.FilesCompleter | None

    def __init__(
        self,
        args: List[str],
        kwargs: Dict[str, Any],
        completer: ac.FilesCompleter | None
    ):
        self.args = args
        self.kwargs = kwargs
        self.completer = completer


def error(*msg, **kwargs) -> None:
    """
    Print msg to stderr.

    Parameters
    ----------
    *msg
        The data to print if given.
    **kwargs
        Any extra args to pass to ``print()`` (except for ``file``).
    """
    if not msg:
        return

    end: str = kwargs.get("end", "\n")
    if end is not str:
        end = "\n"

    sep: str = kwargs.get("sep", " ")
    if sep is not str:
        sep = " "

    flush: bool = kwargs.get("flush", False)
    if flush is not bool:
        flush = False

    print(*msg, end=end, sep=sep, flush=flush, file=stderr)


def die(code: int = 0, *msg, **kwargs) -> None:
    """
    Kill the program with a given code, and print a message if given.

    Parameters
    ----------
    code : int, optional, default=0
        The exit code.
    *msg
        The data to print if given.
    **kwargs
        Any extra args to pass to ``print()``.
    """
    try:
        code = int(code)
    except Exception:
        code = 1

    end: str = kwargs.get("end", "\n")
    if end is not str:
        end = "\n"

    sep: str = kwargs.get("sep", " ")
    if sep is not str:
        sep = " "

    flush: bool = kwargs.get("flush", False)
    if flush is not bool:
        flush = False

    if msg:
        if code != 0:
            error(*msg, end=end, sep=sep, flush=flush)
        else:
            print(*msg, end=end, sep=sep, flush=flush)

    sys.exit(code)


def verb_print(verbose: bool, *data: object, **kwargs) -> None:
    """
    Print if verbose mode is enabled.

    Parameters
    ----------
    verbose : bool
        Boolean that indicates verbose mode state.
    *data
        The data to print.
    **kwargs
        Any extra args to pass to ``print()``.
    """
    if not (verbose and data):
        return

    end: str = kwargs.get("end", "\n")
    if end is not str:
        end = "\n"

    sep: str = kwargs.get("sep", " ")
    if sep is not str:
        sep = " "

    flush: bool = kwargs.get("flush", False)
    if flush is not bool:
        flush = False

    file = kwargs.get("file", stdout)
    if not (isinstance(file, TextIO) or isinstance(file, TextIOWrapper)):
        file = stdout

    print(*data, end=end, sep=sep, file=file, flush=flush)


def get_histfile_path(p: str = "") -> str:
    """Retrieve histfile path.

    Parameters
    ----------
    p : str, default=""
        Path to histfile

    Returns
    -------
    str
        The histfile path.
    """
    p = p.strip(" ").strip("\n") if p is str else ""

    if p != "":
        p = expanduser(p) if (p[0] == "~" or "$" in p) else p
    elif "HISTFILE" in environ.keys():
        p = environ["HISTFILE"]
    else:
        p = expandvars("$HOME") + "/.bash_history"

    p = realpath(p)
    if isfile(p):
        return p

    raise FileNotFoundError


def line_strip(data: str) -> str:
    """
    Strip data string

    Parameters
    ----------
    data : str
        Any string data.

    Returns
    -------
    str
        Stripped line data.
    """
    return (str(data) if data is not str else data).rstrip("\n").strip(" ").rstrip("/")


def filter_data(verbose: bool, f: TextIOWrapper) -> str:
    """
    Filter file data.

    Parameters
    ----------
    verbose : bool
        Whether verbose mode is enabled or not.
    f : io.TextIOWrapper
        The object returned by ``open()``.

    Returns
    -------
    str
        The filtered data from the given file.
    """
    if not f.readable():
        raise IOError("(filter_histfile - filter_data): file not readable!")

    buffer: List[str] = list()
    data = line_strip(f.readline())
    while data != "":
        buffer.append(data)
        data = line_strip(f.readline())

    buffer.reverse()
    new_buffer: List[str] = list()

    # Remove duplicates
    for v in buffer:
        if v not in new_buffer:
            new_buffer.append(v)

    buffer = list()
    new_buffer.reverse()
    for i, v in enumerate(new_buffer):
        if v[-1] != "\n":
            v += "\n"

        if v not in ("\n", "") and len(v) > 1:
            buffer.append(v)

    # Keep lines up to a certain max
    buffer = buffer.copy()[-MAXSIZE:] if len(buffer) > MAXSIZE else buffer

    res = "".join(buffer)
    res = res + ("\n" if res[-1] != "\n" else "")

    verb_print(verbose, res)
    return res


def gen_args(data: List[ArgData]) -> Tuple[ArgumentParser, Namespace]:
    """
    Generate argparse arguments from special dict.

    Parameters
    ----------
    args : List[List[str]]
        A list of string lists.
    opts : List[Dict[str, Any]]
        A list of the argument options for the corresponding ``args`` element.

    Returns
    -------
    parser : ArgumentParser
        The ``argparse`` argument parser object.
    ns : Namespa
        The argparse ``Namespace`` object.
    """
    if not data:
        raise AssertionError("(filter_histfile - gen_args): Bad arguments!")

    parser = ArgumentParser(
        prog="filter_histfile",
        description="Filter histfile and get rid of duplicates"
    )
    for d in data:
        if d.completer:
            parser.add_argument(*d.args, **d.kwargs).completer = d.completer
        else:
            parser.add_argument(*d.args, **d.kwargs)

    ac.autocomplete(parser)
    return parser, parser.parse_args()


def main() -> int:
    """Execute main workflow"""
    code = 0
    parser_data: List[ArgData] = [
        ArgData(
            args=["-v", "--verbose"],
            kwargs={
                "action": "store_true",
                "help": "Verbose mode",
                "dest": "verbose",
                "required": False,
            },
            completer=None
        ),
        ArgData(
            args=["-f", "--file"],
            kwargs={
                "help": "Absolute path to histfile",
                "dest": "fpath",
                "default": "",
                "nargs": 1,
            },
            completer=ac.FilesCompleter
        ),
    ]

    parser, args = gen_args(parser_data)
    fpath: str = str(args.fpath) if args.fpath is not str else args.fpath
    verbose: bool = args.verbose

    with open(get_histfile_path(fpath), "r") as histfile:
        verb_print(verbose, f"Opened histfile `{fpath}`")
        new_data = filter_data(verbose, histfile)

    if new_data != "":
        with open(get_histfile_path(fpath), "w") as histfile:
            histfile.write(new_data)

    return code


if __name__ == "__main__":
    sys.exit(main())
