#!/usr/bin/env python3
# -*- coding: utf8 -*-
"""List all files matching the given regex, per file extension."""
import io
import sys
from argparse import ArgumentParser, Namespace
from os import walk
from os.path import expanduser, isdir, isfile, realpath
from re import Pattern, compile
from sys import stderr, stdout
from typing import Any, Dict, List, TextIO, Tuple

VERBOSE: bool = False


class ArgData:
    """
    Data to be passed to the argument parser.

    Attributes
    ----------
    args : List[str]
        List of strings representing the options to create.
    kwargs : Dict[str, Any]
        A key-value representation of every parameter to be passed
        to ``ArgumentParser.add_argument()``.

    Parameters
    ----------
    args : List[str]
        List of strings representing the options to create.
    kwargs : Dict[str, Any]
        A key-value representation of every parameter to be passed
        to ``ArgumentParser.add_argument()``.
    """

    args: List[str]
    kwargs: Dict[str, Any]

    def __init__(
        self,
        args: List[str],
        kwargs: Dict[str, Any],
    ):
        self.args = args
        self.kwargs = kwargs


def verb_print(*msg, **kwargs) -> None:
    """Print data ONLY if ``verbose`` is ``True``."""
    if not (msg and VERBOSE):
        return

    end: str = kwargs.get("end", "\n")
    sep: str = kwargs.get("sep", " ")
    flush: bool = kwargs.get("flush", False)
    file: TextIO = kwargs.get("file", stdout)

    print(*msg, end=end, sep=sep, flush=flush, file=file)


def error(*msg, **kwargs) -> None:
    """Print msg to stderr."""
    if not msg:
        return

    end: str = kwargs.get("end", "\n")
    sep: str = kwargs.get("sep", " ")
    flush: bool = kwargs.get("flush", False)

    print(*msg, end=end, sep=sep, flush=flush, file=stderr)


def die(code: int = 0, *msg, **kwargs) -> None:
    """
    Kill the program with a given code, and print a message if given.

    Parameters
    ----------
    code : int, optional, default=0
        The exit code.
    *msg
        The data to print if given.
    **kwargs
        Any extra args to pass to ``print()``.
    """
    try:
        code = int(code)
    except Exception:
        code = 1

    end: str = kwargs.get("end", "\n")
    sep: str = kwargs.get("sep", " ")
    flush: bool = kwargs.get("flush", False)

    if msg:
        if code != 0:
            error(*msg, end=end, sep=sep, flush=flush)
        else:
            print(*msg, end=end, sep=sep, flush=flush)

    sys.exit(code)


def search_file(path: str, query: Pattern[str]) -> Tuple[bool, int]:
    """Search query inside the given file."""
    file: io.TextIOWrapper = io.open(path, encoding="utf-8", mode="r")
    data: str = ""
    try:
        data = file.read()
    except Exception:
        verb_print(f"Skipping `{path}`", file=stderr)
    finally:
        file.close()

    found: bool = data != "" and query.search(data) is not None
    return found, (len(query.findall(data)) if data != "" else 0)


def find_files(fexts: List[str], dir: str = ".") -> List[str]:
    """Find all the matching file extensions."""
    directory: str
    dirnames: List[str]
    filenames: List[str]
    matches: List[str] = list()
    for directory, dirnames, filenames in walk(dir, followlinks=False):
        for file in filenames:
            if "." not in file:
                continue

            file_split = file.split(".")
            for fext in fexts:
                if file_split[-1] == fext:
                    matches.append(f"{directory}/{file}")
                    break

    return matches


def gen_args(data: List[ArgData]) -> Tuple[ArgumentParser, Namespace]:
    """
    Generate argparse arguments from special dict.

    Parameters
    ----------
    args : List[List[str]]
        A list of string lists.
    opts : List[Dict[str, Any]]
        A list of the argument options for the corresponding ``args`` element.

    Returns
    -------
    parser : ArgumentParser
        The ``argparse`` argument parser object.
    ns : Namespa
        The argparse ``Namespace`` object.
    """
    if not data:
        raise AssertionError("(find_regexp - gen_args): Bad arguments!")

    parser = ArgumentParser(
        description="List files matching the given regex, per file extension",
        prog="find_regexp")
    for d in data:
        parser.add_argument(*d.args, **d.kwargs)

    return parser, parser.parse_args()


def main() -> int:
    """Execute main workflow."""
    global VERBOSE
    parser, ns = gen_args([
        ArgData(
            args=["directory"],
            kwargs={
                "default": None,
                "help": "The target directory",
                "metavar": "DIRECTORY",
                "nargs": "?",
            },
        ),
        ArgData(args=["-c", "--count"],
                kwargs={
                    "action": "store_true",
                    "dest": "count",
                    "help": "Prints how many matches were found for each file",
                    "required": False,
                }),
        ArgData(args=["-v", "--verbose"],
                kwargs={
                    "action": "store_true",
                    "dest": "verbose",
                    "help": "Enables verbose mode",
                    "required": False,
                }),
        ArgData(args=["-e", "--extensions"],
                kwargs={
                    "action": "extend",
                    "default": [],
                    "dest": "extensions",
                    "help": "The file extensions to search through",
                    "metavar": "FEXT",
                    "nargs": "+",
                    "required": True,
                }),
        ArgData(args=["-q", "--query"],
                kwargs={
                    "dest": "query",
                    "help": "The regex query to search for",
                    "metavar": "QUERY",
                    "nargs": 1,
                    "required": True,
                    "type": str,
                }),
        ArgData(args=["-s", "--sort"],
                kwargs={
                    "action": "store_true",
                    "dest": "sort",
                    "help": "Whether to sort the output",
                    "required": False,
                })
    ])

    query: str = ns.query[0]
    VERBOSE = ns.verbose
    sort: bool = ns.sort
    directory: str = realpath(expanduser(
        ns.directory)) if ns.directory is not None else "."
    extensions: List[str] = ns.extensions
    count: bool = ns.count
    if len(extensions) == 0:
        die(127, "No extensions given!")

    if not isdir(directory):
        die(1, f"Not a directory: `{directory}`")

    files = find_files(extensions, dir=directory)
    if len(files) == 0:
        die(1, "No extensions found!")

    if query == "":
        die(1, "No query given!")

    if sort:
        files.sort()

    comp_query: Pattern[str] = compile(query)
    found: bool = False
    for file in files:
        matched, n_matches = search_file(file, comp_query)
        if matched:
            found = True
            print(file if not count else f"{file}   ==>   {n_matches}")

    return 0 if found else 1


if __name__ == "__main__":
    sys.exit(main())
