#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""A newline removal script."""
import sys
from argparse import ArgumentParser, Namespace
from io import TextIOWrapper
from os.path import isdir, isfile, realpath
from typing import List


def read_file_contents(path: str) -> List[str]:
    """
    Read contents from a file and return a list with all lines.

    Parameters
    ----------
    path : str
        The file path.

    Returns
    -------
    List[str]
        The lines of the file.

    Raises
    ------
    FileNotFoundError
        When the given path is not a file.
    """
    full_path: str = realpath(path)
    if not (isfile(full_path) or isdir(full_path)):
        raise FileNotFoundError(f"Path is not a file: `{full_path}`")

    if isdir(full_path):
        raise FileNotFoundError(f"Path is a directory: `{full_path}`")

    with open(full_path, "r") as file:
        data: List[str] = file.read().split("\n")

    return data


def strip_newlines(data: List[str]) -> str:
    """
    Strip all newlines at the end of file.

    Parameters
    ----------
    data : List[str]
        The lines of the file.

    Returns
    -------
    str
        The full string to be written into the file.
    """
    if len(data) == 0:
        return ""

    data.reverse()
    while data[0] == "":
        data.remove("")

    data.reverse()
    return "\n".join(data)


def main() -> int:
    """
    Execute main script workflow.

    Returns
    -------
    int
        The exit code for the script.
    """
    parser: ArgumentParser = ArgumentParser(
        prog="nwl_rml",
        description="Remove all newlines from a file (including the EOL)."
    )
    parser.add_argument(
        "files",
        nargs="+",
        help="The input file path(s)",
        metavar="</path/to/file>",
    )
    ns: Namespace = parser.parse_args()
    files: List[str] = ns.files

    for file in files:
        data = strip_newlines(read_file_contents(file))

        f: TextIOWrapper = open(file, "w")
        f.write(data)
        f.close()

    return 0


if __name__ == "__main__":
    sys.exit(main())
