#
# ~/.bash_profile
#
# shellcheck shell=bash disable=SC1091,SC2237,SC2016,SC2046 enable=require-double-brackets

[[ "$XDG_SESSION_TYPE" = "wayland" ]] && export MOZ_ENABLE_WAYLAND=1
if [[ -f "$HOME/.bashrc" ]]; then
    . "$HOME/.bashrc" || printf "BAD SOURCING!\n" > /dev/null
fi

# Added by `rbenv init` on Fri 27 Feb 2026 18:28:16 CST
eval "$(rbenv init - --no-rehash bash)"
