#
# ~/.bash_profile
#
# shellcheck shell=bash disable=SC2237,SC2016,SC2046 enable=require-double-brackets

[[ "$XDG_SESSION_TYPE" = "wayland" ]] && export MOZ_ENABLE_WAYLAND=1
if [[ -f "$HOME/.bashrc" ]]; then
    . "$HOME/.bashrc"
fi

# vim:ft=bash:ts=4:sts=4:sw=4:et:ai:si:sta:
